variable "cloudflare_api_key" {}
variable "cloudflare_email" {}
variable "tailscale_api_key" {}
variable "tailscale_domain" {}
variable "homelab_0_ip" {}
variable "homelab_1_ip" {}
variable "homelab_2_ip" {}
variable "homelab_3_ip" {}
variable "homelab_4_ip" {}
