{
 "title": "OpenFaas",
 "description": "OpenFaaS dashboard",
 "tags": [ "openfaas" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": "prometheus" },
   {
    "name": "function",
    "label": "Function",
    "query": "label_values(gateway_service_count, function_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "TOTAL INVOCATIONS CHANGE IN 1 MINUTE",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gateway_function_invocation_total{function_name=\"$function\"}[1m])*60)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "$function",
     "region": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "AVERAGE EXECUTION DURATIONS CHANGE IN 1 MINUTE",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gateway_functions_seconds_sum{function_name=\"$function\"}[1m])*60) / sum(rate(gateway_functions_seconds_count{function_name=\"$function\"}[1m])*60) * 1000",
     "legendFormat": "$function"
    }
   ]
  },
  {
   "title": "SERVICE UP/DOWN",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum(gateway_service_count{function_name=\"$function\"}) > 0)*100/count(sum(gateway_service_count{function_name=\"$function\"})) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "TOTAL INVOCATIONS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "format": "none",
   "valueName": "range",
   "targets": [
    {
     "expr": "sum(gateway_function_invocation_total{function_name=\"$function\"})"
    }
   ]
  },
  {
   "title": "HTTP REQUESTS CODE CHANGE IN 1 MINUTE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gateway_function_invocation_total{function_name=\"$function\", code=\"200\"}[1m])*60)",
     "legendFormat": "$function - HTTP 200"
    },
    {
     "expr": "sum(rate(gateway_function_invocation_total{function_name=\"$function\", code=\"400\"}[1m])*60)",
     "legendFormat": "$function - HTTP 400"
    },
    {
     "expr": "sum(rate(gateway_function_invocation_total{function_name=\"$function\", code=\"404\"}[1m])*60)",
     "legendFormat": "$function - HTTP 404"
    },
    {
     "expr": "sum(rate(gateway_function_invocation_total{function_name=\"$function\", code=\"429\"}[1m])*60)",
     "legendFormat": "$function - HTTP 429"
    },
    {
     "expr": "sum(rate(gateway_function_invocation_total{function_name=\"$function\", code=\"500\"}[1m])*60)",
     "legendFormat": "$function - HTTP 500"
    },
    {
     "expr": "sum(rate(gateway_function_invocation_total{function_name=\"$function\", code=\"503\"}[1m])*60)",
     "legendFormat": "$function - HTTP 503"
    }
   ]
  },
  {
   "title": "GATEWAY SERVICE COUNT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 11, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(gateway_service_count{function_name=\"$function\"})",
     "legendFormat": "$function"
    }
   ]
  },
  {
   "title": "AVERAGE RESPONSE TIME",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 9 },
   "format": "ms",
   "valueName": "range",
   "targets": [
    {
     "expr": "sum(gateway_functions_seconds_sum{function_name=\"$function\"}) / sum(gateway_functions_seconds_count{function_name=\"$function\"}) * 1000"
    }
   ]
  }
 ]
}