someValue: ENC[AES256_GCM,data:rOTZKnk=,iv:7v9po66e3MQ3ysN5hnOxxHeYu/h6NeCbEmvst/tOWRk=,tag:2k2YfCqUQL4jUM199PheWw==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-02-22T01:00:09Z'
    mac: ENC[AES256_GCM,data:Was9QdRTIkayaAz2YQngJA354Cb5e+XG6qMD0RMsXZs/VcVE8V/hVeEx7DJQKGS01A/FG6JmWkOQ+wJPuVFp4/rDAmmOmugtY4xRWqkcB39O7DbmXP6ho+pu3BbxKPiGhCtevto19sRNUu3juiEsW+O+M+u0EF8qXbc43PciZqA=,iv:uTIXPgrYCXjvNRTYoOC5nOUiQk4G13cdlxDx9pVqQ3E=,tag:zOlSEcDr0qHfGkhOn2ELIQ==,type:str]
    pgp:
    -   created_at: '2021-02-22T01:00:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/NKTSBqvTB6ARAAoVDfVz0G+PvFp4q1K1Cj1icF4o6nM1ByIWg9IjYtOSHG
            geekNRi0kgF9mq8gupYFrzB5eM4Idf82iZfTvxC0MTwVP25S36AkUunaOih6KPLY
            bmxRR073B8bssEwEWCwCdQ3g4CxWI3oDYc1cYgdMzHpbujv1juoAbzmDppdd3Rvs
            +pCwOpsXbs+ao//Yi8eZX/V4US28A2gOTHUYlUKDlVFWcOiNIkZE+prNus7qlr1s
            z4SVITxLtM2j7Q7+23QZm0KbNztY/edLq0XRmMgaf+9k3BMqyksYjuffTeTCsH0V
            F50fuoTkQO1o0mhRMsU/fEIVtOoySL9s+zCnfIfQ19WRmY7QBCrCtoDJwuVyq5aP
            k3LqDCOTVW1XDK1vTdI3qA/ANAAHSqgGIOEpLm5rFrEUR2ldsUSeS2IgoDM1cgCJ
            pUIG2WM8pQx8E0BUPnafCF5PnX0iu+eBbO1p9Z4hI+ZbVcRL3OwBg9MGqOoYDHb5
            AjRCFqZsF2IPlvVd6yv6kHWeSdif3xiUoZ1w2Mi+gM2Bsoh2mPFEIQJDcvi5gsq8
            u0pLrtzCt/9DUMzhrC0FM/yw3WtgXSkOQd7qF4sibcN7yEJ3e4KIqhFFSvathSLv
            WJRuoYgG47fEwVJ6iKko1Qj+ViYqB+FoV0D5h5MxLEsWfMXKUs/ahv7JyfxkgBjS
            XAHMlvxEFFnQhzGGr2zz4HwXU1wvPQZSMPZE3hE1A3SPJGml2XsA7PfXvahkeITv
            F6oNtWGUbZQPHsUNBk/QEF8aImOBmyso+rP5LCMLij8OZZnZKmNzpAebC3WJ
            =fDKc
            -----END PGP MESSAGE-----
        fp: BC8DF74B855D6575ED4878E8962D032461639065
    unencrypted_suffix: _unencrypted
    version: 3.6.1
