domain: dev.mooncity.dev
environment: dev

spec:
  source:
    repoURL: git@github.com:grahamplata/kubernetes-homelab.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
